//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatime.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.Ranking = new HashSet<Ranking>();
        }
    
        public int idActividad { get; set; }
        public string nombreActividad { get; set; }
        public string lugar { get; set; }
        public string infoActividad { get; set; }
        public string habilidadesRequisitos { get; set; }
        public string imagen { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int idProblema { get; set; }
        public int idPatrocina { get; set; }
        public int idOrganiza { get; set; }
    
        public virtual ONG ONG { get; set; }
        public virtual Problematica Problematica { get; set; }
        public virtual Sponsor Sponsor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranking> Ranking { get; set; }
    }
}
