//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatime.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ONG()
        {
            this.Actividad = new HashSet<Actividad>();
        }
    
        public int idOng { get; set; }
        public string nombreOng { get; set; }
        public string razonSocial { get; set; }
        public string rfc { get; set; }
        public string domicilio { get; set; }
        public string objetivoSocial { get; set; }
        public string actividades { get; set; }
        public decimal apoyosVoluntarios { get; set; }
        public System.DateTime inicioOperacion { get; set; }
        public Nullable<System.DateTime> tiempoOperacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
    }
}
