//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatime.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int idRanking { get; set; }
        public int cantidadHoras { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public int idVoluntario { get; set; }
        public int idActividad { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Voluntario Voluntario { get; set; }
    }
}
