//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatime.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int idSponsor { get; set; }
        public string nombreEmpresa { get; set; }
        public string direccion { get; set; }
        public string numTelefono { get; set; }
        public string email { get; set; }
        public string rfc { get; set; }
    
        public virtual Actividad Actividad { get; set; }
    }
}
