//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatime.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voluntario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voluntario()
        {
            this.Ranking = new HashSet<Ranking>();
        }
    
        public int idVoluntario { get; set; }
        public string imagenPerfil { get; set; }
        public string nombre { get; set; }
        public string municipio { get; set; }
        public string comunidad { get; set; }
        public string colonia { get; set; }
        public string direccion { get; set; }
        public string numTelOficina { get; set; }
        public string numCelular { get; set; }
        public int idEstado { get; set; }
        public int idEscolaridad { get; set; }
    
        public virtual Escolaridad Escolaridad { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranking> Ranking { get; set; }
    }
}
